
services:
  devopsdb:
    image: shaikmustafa/deepika:db
    ports:
      - "3306:3306"
    deploy:
      replicas: 1
    networks:
      - mynetwork

  application:
    image: shaikmustafa/deepika:app
    ports:
      - "1111:8081"
    deploy:
      replicas: 3
    depends_on:
      - devopsdb
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: overlay
