
services:
  devopsdb:
    image: sumerasulthana/flm-oct:db
    ports:
      - "1115:3306"
    deploy:
      replicas: 1
    

  application:
    image: sumerasultha/flm-oct:javaapp
    ports:
      - "1116:8081"
    deploy:
      replicas: 1
    depends_on:
      - devopsdb
 


